# Generated by Django 4.0.4 on 2022-06-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=256)),
                ('order_time', models.TextField(blank=True, max_length=256)),
                ('order_all_price', models.TextField(blank=True, max_length=256)),
                ('discount_rate', models.TextField(blank=True, max_length=256)),
                ('total_price', models.TextField(blank=True, max_length=256)),
                ('exists_order', models.TextField(blank=True, max_length=256)),
                ('order_complete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'db_table': 'userorder',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.TextField(blank=True, max_length=256)),
                ('order_complete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'db_table': 'productorder',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(blank=True, max_length=256)),
                ('product_img', models.TextField(blank=True, max_length=256)),
                ('product_desc', models.TextField(blank=True, max_length=256)),
                ('product_price', models.TextField(blank=True, max_length=256)),
                ('product_stock', models.TextField(blank=True, max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
