# Generated by Django 4.0.4 on 2022-06-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_userorder_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_complete', models.TextField(blank=True, max_length=256)),
                ('money_complete', models.TextField(blank=True, max_length=256)),
                ('order_cancel', models.TextField(blank=True, max_length=256)),
                ('send_start', models.DateTimeField()),
                ('send_complete', models.DateTimeField()),
            ],
            options={
                'db_table': 'my_order',
            },
        ),
    ]
