# Generated by Django 4.0.4 on 2022-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, max_length=256)),
                ('password', models.TextField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'my_user',
            },
        ),
    ]
